### ISSUE TITLE
Getting drip-dot-net from NuGet

### ISSUE THREAD

**Issue by odendoak** [DripEmail/drip-dot-net#6]
> ### NuGet
> File a request if you're interested in this. For now see below.

It would be awesome if I could install drip-dot-net as a package from NuGet.

**Comment by uluhonolulu** [comment]
Agreed. Drip's promise is "our sole purpose, nay our mission, is to make it insanely easy and user-friendly to get started". Building from source and having to update it manually is so 90's and so far from the stated mission.

**Comment by rwalling** [comment]
Thanks for the suggestion. I'd love to do this for all of our wrappers, but building from source is how we need to offer all of our libraries for now (PHP, Ruby, .NET). The admin headache of dealing with each repo that uses their own formats, etc... isn't feasible for a small team like ours, unfortunately. We're seeing startups who aren't even launching API wrappers due to the amount of time/resources required to go across all the languages people request.

So I'm closing this for now and will re-open when we get to the point that this is feasible.

**Comment by uluhonolulu** [comment]
Ok, I understand that. So no use in sending pull requests?
